version: "3.8"
services:
  db-auth:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: authDb
  db-article:
    image: postgres:13.2-alpine
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: articleDb